project:
  type: website
  output-dir: docs
website:
  title: "COSY"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - publicaciones.qmd
      - software.qmd
      - datasets.qmd
      - videos.qmd
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

